### ISSUE TITLE
Find Q1 Solution

### ISSUE THREAD

**Issue by SandeepanM2003** [SandeepanM2003/cpp_python_codes#1]

**Comment by amritpalsingh52** [comment]
i have purposed a solution of this please push it

**Comment by SandeepanM2003** [comment]
Yes I have pushed your code.

**Comment by amritpalsingh52** [comment]
Dear sir ...
Thanks for your reply and pushing my code...i also have snd request to you
on LinkedIn .. regarding my view and connection request. Will you please
accept my request? And also I have make another pull requests please check
them and if you feel like I have did something as you wanted then please
let me know about it also ...

**Comment by SandeepanM2003** [comment]
Issue solved by @amritpalsingh52
