### ISSUE TITLE
Solve Q3 number theory problem in issue folder

### ISSUE THREAD

**Issue by SandeepanM2003** [SandeepanM2003/cpp_python_codes#10]
Any up to solve it?
Looking forward to your optimised solutions.
Submit your answers in C++ or python according to the language you preferred to find the solution.

**Comment by anikagarwa12** [comment]
kindly assign me this and add hacktoberfest label

**Comment by SandeepanM2003** [comment]
@anikagarwa12  I have assigned you the issue.Kindly submit your best solution in the respective folders(C++/Python)

**Comment by anikagarwa12** [comment]
@SandeepanM2003  definitely

**Comment by ankitmwd01** [comment]
please assign me this task
