### ISSUE TITLE
Solve DP Problem Q2 in issue folder

### ISSUE THREAD

**Issue by SandeepanM2003** [SandeepanM2003/cpp_python_codes#8]
Looking forward to your optimised solutions.
Submit your answers in C++ or python according to the language you preferred to find the solution.

**Comment by kittoteja** [comment]
hey , I like to contribute

**Comment by SandeepanM2003** [comment]
@kittoteja  I have assigned that issue to you.If you using C++ then submit the code in C++ folder or if python then python folder.

**Comment by SandeepanM2003** [comment]
@kittoteja merged your pull request
